import { BASE_URL } from "@/lib/constants";
import { FrameActionPayload, getFrameHtml } from "frames.js";
import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
    let body: FrameActionPayload = await req.json();

    let { inputText } = body.untrustedData;

    // Does URL have texts?
    let previousURL = new URL(req.url);
    let textsRaw = previousURL.searchParams.get("texts");

    let texts = [];
    if (textsRaw) {
        texts = JSON.parse(textsRaw);
    }

    // How many texts does URL have?
    let step = 1;
    if (texts.length) {
        step = texts.length;
    }

    texts.push(inputText);
    console.log(texts, step);

    let image = `${BASE_URL}/api/meme-template?texts=`;

    let encodedTexts = encodeURIComponent(JSON.stringify(texts));

    if (texts.length >= 3) {
        let encodedMessage = encodeURIComponent(
            "This meme was generated by a frame created by @harpaljadeja"
        );

        console.log(image + encodedTexts + encodeURIComponent(".png"));

        return new NextResponse(
            getFrameHtml({
                version: "vNext",
                image: image + encodedTexts,
                imageAspectRatio: "1:1",
                buttons: [
                    {
                        label: "Share",
                        action: "link",
                        target: `https://warpcast.com/~/compose?text=${encodedMessage}&embeds[]=${
                            image + encodedTexts + encodeURIComponent(".png")
                        }`,
                    },
                ],
                postUrl: `${BASE_URL}/api/post_url?texts=` + encodedTexts,
            })
        );
    }

    return new NextResponse(
        getFrameHtml({
            version: "vNext",
            image: image + encodedTexts,
            imageAspectRatio: "1:1",
            inputText: `Text ${step + 1}`,
            buttons: [
                {
                    label: "Submit",
                    action: "post",
                },
            ],
            postUrl: `${BASE_URL}/api/post_url?texts=` + encodedTexts,
        })
    );
}
